from __future__ import annotations

import re
from functools import lru_cache
from typing import Dict, Iterable, List, Set


SCHEMA_VERSION = "1.0.0"

NODE_TYPES = {
    "muscle",
    "nerve",
    "vessel",
    "bone",
    "joint",
    "anatomical_space",
    "posture_pattern",
    "movement_pattern",
    "symptom",
    "mechanism",
    "test",
    "intervention",
    "red_flag",
    "condition",
    "concept",
    "article",
    "section",
    "evidence_span",
}

RELATION_TYPES = {
    "mentioned_with",
    "located_in",
    "passes_through",
    "compresses",
    "may_compress",
    "irritates",
    "may_irritate",
    "narrows",
    "widens",
    "alters_alignment_of",
    "contributes_to",
    "may_contribute_to",
    "associated_with",
    "can_mimic",
    "differentiated_from",
    "may_produce",
    "innervates",
    "supplies",
    "stabilizes",
    "elevates",
    "depresses",
    "upwardly_rotates",
    "downwardly_rotates",
    "anteriorly_tilts",
    "posteriorly_tilts",
    "tests_for",
    "contraindicated_by",
    "red_flag_for",
    "supported_by",
    "requires_caution",
}

SUPPORT_LEVELS = {
    "direct",
    "indirect",
    "inferred_from_same_section",
    "inferred_from_path",
    "weak",
    "unsupported",
}

CLAIM_STRENGTHS = {"strong", "moderate", "weak", "speculative"}
CLINICAL_RISKS = {"low", "medium", "high"}

CLAIM_TYPES = {
    "anatomical_fact",
    "author_claim",
    "mechanism_claim",
    "symptom_claim",
    "test_claim",
    "intervention_claim",
    "safety_claim",
    "uncertainty_claim",
}

CLINICAL_POLICIES = {
    "safe_to_explain_as_mechanism",
    "explain_as_possible_indirect_mechanism",
    "requires_differential_screening",
    "requires_red_flag_screening",
    "do_not_present_as_causal_conclusion",
}


ENTITY_GROUPS: Dict[str, Dict[str, List[str]]] = {
    "muscle": {
        "scalene": ["scalene", "scalenes", "scalene muscle", "scalene muscles", "scalene dysfunction"],
        "anterior scalene": ["anterior scalene"],
        "middle scalene": ["middle scalene"],
        "levator scapulae": ["levator scapulae", "levator scapula"],
        "trapezius": ["trapezius", "traps"],
        "pectoralis minor": ["pectoralis minor", "pec minor", "pectoralis minor muscle"],
        "sternocleidomastoid": ["sternocleidomastoid", "scm"],
        "serratus anterior": ["serratus anterior"],
        "rhomboids": ["rhomboids", "rhomboid"],
        "teres minor": ["teres minor"],
        "teres major": ["teres major"],
        "rotator cuff": ["rotator cuff", "rotator cuff muscles"],
        "supraspinatus": ["supraspinatus"],
        "subscapularis": ["subscapularis"],
        "psoas": ["psoas", "psoas major", "iliopsoas"],
        "iliacus": ["iliacus"],
        "gluteus maximus": ["gluteus maximus", "glute max"],
        "gluteus medius": ["gluteus medius", "glute med"],
        "piriformis": ["piriformis"],
        "obturator internus": ["obturator internus"],
        "tensor fascia latae": ["tensor fascia latae", "tfl"],
        "quadratus lumborum": ["quadratus lumborum", "ql"],
        "lumbar extensors": ["lumbar extensors", "back extensors"],
        "hamstrings": ["hamstrings", "hamstring"],
        "quadriceps": ["quadriceps", "quad", "quads"],
        "gastrocnemius": ["gastrocnemius", "calf muscle"],
        "popliteus": ["popliteus"],
        "pterygoids": ["pterygoids", "lateral pterygoid", "medial pterygoid"],
        "lateral pterygoid": ["lateral pterygoid", "lateral pterygoids"],
        "medial pterygoid": ["medial pterygoid", "medial pterygoids"],
        "masseter": ["masseter"],
        "temporalis": ["temporalis"],
        "tensor tympani": ["tensor tympani", "tensor tympani muscle"],
        "tensor veli palatini": ["tensor veli palatini"],
        "suboccipitals": ["suboccipitals", "suboccipital muscles"],
        "longus colli": ["longus colli"],
        "longus capitis": ["longus capitis"],
        "supinator": ["supinator"],
        "pronator teres": ["pronator teres"],
    },
    "nerve": {
        "brachial plexus": ["brachial plexus"],
        "lumbar plexus": ["lumbar plexus", "lpcs", "lumbar plexus compression"],
        "lumbosacral plexus": ["lumbosacral plexus", "lumbo-sacral plexus"],
        "sacral plexus": ["sacral plexus"],
        "pudendal nerve": ["pudendal nerve"],
        "inferior hypogastric plexus": ["inferior hypogastric plexus", "hypogastric plexus"],
        "femoral nerve": ["femoral nerve", "femoral"],
        "sciatic nerve": ["sciatic nerve"],
        "ilioinguinal nerve": ["ilioinguinal nerve", "ilioinguinal"],
        "iliohypogastric nerve": ["iliohypogastric nerve"],
        "genitofemoral nerve": ["genitofemoral nerve", "genitofemoral"],
        "lateral femoral cutaneous nerve": ["lateral femoral cutaneous nerve", "lateral femoral cutaneous"],
        "nerve root": ["nerve root", "nerve roots", "lumbar nerve root", "spinal nerve root"],
        "cervical plexus": ["cervical plexus"],
        "dorsal scapular nerve": ["dorsal scapular nerve"],
        "accessory nerve": ["accessory nerve", "spinal accessory nerve"],
        "occipital nerves": ["occipital nerves", "occipital nerve", "greater occipital nerve", "lesser occipital nerve", "third occipital nerve", "3rd occipital nerve", "greater occipital", "lesser occipital", "3rd occipital"],
        "mandibular nerve": ["mandibular nerve", "mandibular (trigeminal) nerve", "mandibular branch", "v3"],
        "maxillary nerve": ["maxillary nerve", "maxillary branch", "v2"],
        "ophthalmic nerve": ["ophthalmic nerve", "ophthalamic", "ophthalmic branch", "v1"],
        "buccal nerve": ["buccal nerve", "buccal branch"],
        "lingual nerve": ["lingual nerve", "lingual branch"],
        "ulnar nerve": ["ulnar nerve", "ulnar"],
        "median nerve": ["median nerve"],
        "radial nerve": ["radial nerve", "radial"],
        "axillary nerve": ["axillary nerve", "axillary"],
        "musculocutaneous nerve": ["musculocutaneous nerve"],
        "phrenic nerve": ["phrenic nerve"],
        "vestibulocochlear nerve": ["vestibulocochlear nerve", "eighth cranial nerve", "cranial nerve viii"],
        "trigeminal nerve": ["trigeminal nerve", "cranial nerve v"],
        "facial nerve": ["facial nerve", "cranial nerve vii"],
        "glossopharyngeal nerve": ["glossopharyngeal nerve", "cranial nerve ix"],
        "vagus nerve": ["vagus nerve", "cranial nerve x"],
        "auriculotemporal nerve": ["auriculotemporal nerve"],
        "inferior trunk": ["inferior trunk"],
        "middle trunk": ["middle trunk"],
        "superior trunk": ["superior trunk"],
    },
    "vessel": {
        "subclavian artery": ["subclavian artery"],
        "subclavian vein": ["subclavian vein"],
        "vertebral artery": ["vertebral artery"],
        "vertebral vein": ["vertebral vein"],
        "internal jugular vein": ["internal jugular vein", "ijv", "jugular vein", "jugular venous", "jugular outflow"],
        "external jugular vein": ["external jugular vein"],
        "internal carotid artery": ["internal carotid artery", "carotid artery"],
        "basilar artery": ["basilar artery"],
        "venous sinus": ["venous sinus", "venous sinuses", "dural venous sinus"],
    },
    "bone": {
        "clavicle": ["clavicle", "clavicular", "collarbone"],
        "first rib": ["first rib", "1st rib"],
        "scapula": ["scapula", "scapular", "shoulder blade"],
        "atlas": ["atlas", "c1"],
        "axis": ["c2"],
        "odontoid process": ["odontoid process", "odontoid", "dens"],
        "mandible": ["mandible", "jaw", "lower jaw"],
        "temporal bone": ["temporal bone"],
        "maxilla": ["maxilla", "upper jaw"],
        "humerus": ["humerus", "humeral head"],
        "acromion": ["acromion"],
        "coracoid process": ["coracoid", "coracoid process"],
        "femur": ["femur", "femoral head"],
        "acetabulum": ["acetabulum"],
        "pelvis": ["pelvis", "pelvic"],
        "lumbar spine": ["lumbar spine", "lumbar", "lumbosacral spine"],
        "sacrum": ["sacrum"],
        "tibia": ["tibia", "tibial"],
        "patella": ["patella", "kneecap"],
        "fibula": ["fibula"],
    },
    "joint": {
        "temporomandibular joint": ["temporomandibular joint", "tmj"],
        "atlantoaxial joint": ["atlantoaxial joint", "atlantoaxial", "atlanto-axial joint", "atlanto-axial", "a-a joint", "aa joint"],
        "atlanto-occipital joint": ["atlanto-occipital joint", "atlanto-occipital", "atlantooccipital joint", "atlantooccipital", "a-o joint", "ao joint"],
        "hip joint": ["hip joint"],
        "knee joint": ["knee joint"],
        "glenohumeral joint": ["glenohumeral joint", "shoulder joint"],
    },
    "anatomical_space": {
        "costoclavicular space": ["costoclavicular space", "costoclavicular", "costoclavicular narrowing"],
        "costoclavicular passage": ["costoclavicular passage"],
        "interscalene triangle": ["interscalene triangle", "interscalene"],
        "subcoracoid space": ["subcoracoid space", "subcoracoid"],
        "retropectoralis minor space": ["retropectoralis minor space", "retropectoralis", "pectoralis minor space"],
        "thoracic outlet": ["thoracic outlet", "tos space", "thoracic outlet mechanics"],
        "foramen magnum": ["foramen magnum"],
        "jugular foramen": ["jugular foramen"],
        "Alcock's canal": ["alcock's canal", "alcock canal"],
        "pelvic floor": ["pelvic floor"],
        "subacromial space": ["subacromial space", "subacromial"],
        "middle ear": ["middle ear"],
        "eustachian tube": ["eustachian tube"],
        "tympanic plexus": ["tympanic plexus"],
        "vestibular system": ["vestibular system", "labyrinth"],
        "cochlea": ["cochlea"],
        "semicircular canals": ["semicircular canals", "semicircular canal"],
        "utricle": ["utricle"],
        "sacculus": ["sacculus"],
    },
    "posture_pattern": {
        "scapular depression": ["scapular depression", "depressed scapula", "depressed scapulae", "depressed scapular", "scapuloclavicular depression"],
        "anterior scapular tilt": ["anterior scapular tilt", "anteriorly tilted scapula"],
        "downward scapular rotation": ["downward scapular rotation", "downward rotation"],
        "forward head posture": ["forward head posture", "forward head"],
        "swayback posture": ["swayback posture", "swayback"],
        "slouching": ["slouching", "slouched"],
        "scapular dyskinesis": ["scapular dyskinesis", "dyskinesis"],
        "anterior pelvic tilt": ["anterior pelvic tilt", "apt"],
        "posterior pelvic tilt": ["posterior pelvic tilt"],
        "functional varus": ["functional varus", "knee varus"],
        "functional valgus": ["functional valgus", "knee valgus"],
    },
    "movement_pattern": {
        "upward scapular rotation": ["upward scapular rotation", "upward rotation"],
        "posterior scapular rotation": ["posterior scapular rotation", "posterior rotation"],
        "clavicular depression": ["clavicular depression", "clavicular descent", "depressed clavicle"],
        "belly breathing": ["belly breathing", "abdominal breathing"],
        "thoracic breathing": ["thoracic breathing", "chest breathing"],
        "altered breathing mechanics": ["altered breathing mechanics", "breathing mechanics", "poor breathing"],
        "first rib mechanics": ["first rib mechanics", "first-rib mechanics", "first rib position", "first rib elevation"],
        "distal nerve vulnerability": ["distal nerve vulnerability", "distal entrapment", "secondary distal entrapment"],
        "sensitized nervous chain": ["sensitized nervous chain", "sensitized chain", "neural sensitization"],
        "anterior femoral glide": ["anterior femoral glide", "anterior femoral glide syndrome", "fags"],
        "posterior tibial glide": ["posterior tibial glide"],
        "anterior tibial glide": ["anterior tibial glide"],
        "tibial internal rotation": ["tibial internal rotation", "internal tibial rotation"],
        "tibial external rotation": ["tibial external rotation", "external tibial rotation"],
        "scapular winging": ["scapular winging", "winging"],
        "venous outflow impairment": ["venous outflow impairment", "venous outflow", "venous drainage impairment", "venous obstruction", "cranial venous outflow"],
        "protective bracing": ["protective bracing", "bracing", "global involuntary clenching strategy", "gics", "chronic muscle clenching"],
        "motor control": ["motor control", "motor-control"],
        "mouth breathing": ["mouth breathing", "mouth-breathing"],
        "tongue posture": ["tongue posture", "tongue position"],
    },
    "symptom": {
        "numbness": ["numbness", "numb"],
        "paresthesia": ["paresthesia", "paraesthesia", "paresthesias"],
        "tingling": ["tingling", "pins and needles"],
        "neuralgia": ["neuralgia"],
        "neck pain": ["neck pain"],
        "shoulder pain": ["shoulder pain"],
        "chest pain": ["chest pain"],
        "pain between shoulder blades": ["pain between shoulder blades", "pain between their shoulder blades", "interscapular pain"],
        "dorsal scapular pain": ["dorsal scapular pain", "periscapular pain", "periscapular area"],
        "ulnar neuralgia": ["ulnar neuralgia", "ulnar paresthesia", "ulnar paresthesias"],
        "headache": ["headache", "headaches"],
        "migraine": ["migraine", "migraines"],
        "dizziness": ["dizziness", "dizzy"],
        "brain fog": ["brain fog"],
        "dyspnea": ["dyspnea", "shortness of breath"],
        "globus": ["globus", "globus sensation"],
        "tremor": ["tremor", "tremors"],
        "Raynaud's syndrome": ["raynaud's syndrome", "raynaud syndrome", "raynaud's", "raynaud"],
        "causalgia": ["causalgia"],
        "TOS-like symptoms": ["tos symptoms", "tos-like symptoms", "thoracic outlet symptoms", "arm symptoms"],
        "tinnitus": ["tinnitus"],
        "ear pressure": ["ear pressure", "ear fullness", "aural fullness"],
        "hearing symptoms": ["hearing symptoms", "hearing loss", "auditory symptoms"],
        "vestibular symptoms": ["vestibular symptoms", "vestibular impairment", "vestibular dysfunction", "vertigo"],
        "fatigue": ["fatigue", "severe fatigue", "tiredness", "tired"],
        "orthostatic symptoms": ["orthostatic symptoms", "orthostatic intolerance", "syncope", "presyncope"],
        "autonomic symptoms": ["autonomic symptoms", "dysautonomia", "autonomic dysfunction"],
        "hip pain": ["hip pain", "hip groin pain"],
        "groin pain": ["groin pain", "groin"],
        "pelvic pain": ["pelvic pain", "genital pain", "perineal pain"],
        "knee pain": ["knee pain"],
        "low back pain": ["low back pain", "lower back pain", "back pain"],
        "jaw pain": ["jaw pain", "tmj pain"],
    },
    "condition": {
        "thoracic outlet syndrome": ["thoracic outlet syndrome", "tos"],
        "neurogenic TOS": ["neurogenic tos", "ntos", "neurogenic thoracic outlet"],
        "vascular TOS": ["vascular tos", "arterial tos", "venous tos"],
        "costoclavicular syndrome": ["costoclavicular syndrome"],
        "cervical plexus entrapment": ["cervical plexus entrapment", "cervical plexus compression"],
        "brachial plexus compression": ["brachial plexus compression", "compression of the brachial plexus"],
        "neurovascular compression": ["neurovascular compression"],
        "sympathetic involvement": ["sympathetic involvement", "sympathetic"],
        "craniovascular hyperperfusion": ["craniovascular hyperperfusion"],
        "scalene dysfunction": ["scalene dysfunction", "scalene inhibition", "underactive scalenes", "inhibited scalenes"],
        "temporomandibular dysfunction": ["temporomandibular dysfunction", "tmd", "tmj dysfunction"],
        "atlas instability": ["atlas instability", "atlas joint instability", "atlantal instability"],
        "atlantoaxial instability": ["atlantoaxial instability", "aai"],
        "craniocervical instability": ["craniocervical instability", "cci"],
        "intracranial hypertension": ["intracranial hypertension", "intracranial pressure", "ich", "iih", "idiopathic intracranial hypertension", "pseudotumor cerebri"],
        "ME/CFS": ["me/cfs", "me cfs", "myalgic encephalomyelitis", "chronic fatigue syndrome"],
        "POTS": ["pots", "postural orthostatic tachycardia syndrome", "postural orthostatic tachycardia"],
        "lumbar plexus compression syndrome": ["lumbar plexus compression syndrome", "lpcs"],
        "pudendal neuralgia": ["pudendal neuralgia"],
        "inferior hypogastric plexopathy": ["inferior hypogastric plexopathy", "hypogastric plexalgia"],
        "femoroacetabular impingement": ["femoroacetabular impingement", "fai", "hip impingement"],
        "trochanteric bursitis": ["trochanteric bursitis", "hip bursitis"],
        "patellofemoral pain syndrome": ["patellofemoral pain syndrome", "patellofemoral pain", "pfps", "runner's knee", "runners knee"],
        "jumper's knee": ["jumper's knee", "jumpers knee", "patellar tendinopathy"],
        "disc herniation": ["disc herniation", "disc herniations", "disc protrusion", "disc protrusions", "herniated disc", "herniated discs", "herniated intervertebral disc", "herniated intervertebral discs"],
        "shoulder impingement": ["shoulder impingement", "subacromial impingement"],
        "rotator cuff disease": ["rotator cuff disease", "rotator cuff injury"],
    },
    "mechanism": {
        "costoclavicular narrowing": ["costoclavicular narrowing", "narrowing of the costoclavicular", "narrowed costoclavicular"],
        "thoracic outlet mechanics": ["thoracic outlet mechanics", "thoracic outlet alignment"],
        "brachial plexus irritation": ["brachial plexus irritation", "plexus irritation"],
        "neurovascular compression": ["neurovascular compression"],
        "ligament laxity": ["ligament laxity", "ligamentous laxity", "ligamentous rupture"],
        "brainstem compression": ["brainstem compression"],
        "brainstem": ["brainstem", "cervicomedullary junction"],
        "transverse ligament": ["transverse ligament"],
        "alar ligament": ["alar ligament", "alar ligaments"],
        "tectorial membrane": ["tectorial membrane"],
        "jugular outlet obstruction": ["jugular outlet obstruction", "jugular obstruction"],
        "venous sinus stenosis": ["venous sinus stenosis"],
        "CSF pressure": ["csf pressure", "cerebrospinal fluid pressure"],
        "CSF leak": ["csf leak", "cerebrospinal fluid leak"],
        "papilledema": ["papilledema"],
        "mandibular retraction": ["mandibular retraction", "posterior mandibular position"],
        "disc displacement": ["disc displacement", "tmj disc displacement"],
        "labral impingement": ["labral impingement", "hip labrum", "labrum", "labral injury"],
        "lumbar lordosis": ["lumbar lordosis", "lordosis", "hyperlordosis"],
        "disc loading": ["disc loading", "disc compression"],
        "breath holding": ["breath holding", "holding the breath", "valsalva"],
        "occlusion": ["occlusion", "dental occlusion", "bite"],
    },
    "test": {
        "provocative testing": ["provocative testing", "provocative test", "provocative tests"],
        "manual muscle testing": ["manual muscle testing", "mmt"],
        "FABER test": ["faber test", "faber"],
        "dynamic imaging": ["dynamic imaging", "upright mri", "flexion-extension imaging", "ct venogram", "ctv", "manometry"],
        "nerve block": ["nerve block", "pudendal nerve block", "hypogastric plexus block"],
        "Tinel's sign": ["tinel's sign", "tinel sign"],
    },
    "intervention": {
        "postural rehabilitation": ["postural rehabilitation", "posture correction", "postural correction", "posture"],
        "strengthening": ["strengthening", "strengthen", "corrective exercise", "active exercise"],
        "awareness training": ["awareness training", "awareness", "neuromuscular reconfiguration"],
        "surgical decompression": ["surgical decompression", "first rib resection", "scalenotomy", "pectoralis minor tenotomy"],
        "prolotherapy": ["prolotherapy"],
        "fusion surgery": ["fusion surgery", "surgical fusion"],
    },
    "red_flag": {
        "progressive neurologic deficit": [
            "progressive weakness",
            "severe neurologic",
            "new weakness",
            "worsening weakness",
            "progressive neurologic symptoms",
            "progressive neurological symptoms",
            "progressive neurologic deficit",
            "progressive neurological deficit",
        ],
        "bowel or bladder changes": ["bowel or bladder", "bladder changes", "bowel changes"],
        "significant trauma": ["significant trauma", "major trauma"],
        "systemic fever": ["fever", "systemic decline"],
        "brainstem compromise": ["brainstem compromise", "quadriparesis", "paralysis", "stroke-like symptoms"],
        "vertebrobasilar insufficiency": ["vertebrobasilar insufficiency", "vertebrobasilar", "bow hunter's syndrome", "bow hunter syndrome"],
    },
}


def canonical_node_id(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return f"node_{slug}"


@lru_cache(maxsize=1)
def all_entities() -> Dict[str, Dict[str, object]]:
    entities: Dict[str, Dict[str, object]] = {}
    for node_type, names in ENTITY_GROUPS.items():
        for name, aliases in names.items():
            implicit_aliases = set(aliases) if name in {"axis"} else {name, *aliases}
            alias_set = sorted(implicit_aliases, key=lambda s: (len(s), s.lower()))
            entities[name] = {
                "node_id": canonical_node_id(name),
                "canonical_name": name,
                "aliases": alias_set,
                "node_type": node_type,
            }
    return entities


@lru_cache(maxsize=None)
def _alias_patterns_cached(aliases: tuple[str, ...]) -> tuple[re.Pattern[str], ...]:
    patterns = []
    for alias in sorted(set(aliases), key=len, reverse=True):
        escaped = re.escape(alias.lower()).replace("\\ ", r"\s+")
        patterns.append(re.compile(rf"(?<![a-z0-9]){escaped}(?![a-z0-9])", re.I))
    return tuple(patterns)


def alias_patterns(aliases: Iterable[str]) -> List[re.Pattern[str]]:
    return list(_alias_patterns_cached(tuple(sorted(set(aliases)))))


def detect_entities(text: str) -> Set[str]:
    text = text or ""
    found: Set[str] = set()
    for name, data in all_entities().items():
        if any(pattern.search(text) for pattern in alias_patterns(data["aliases"])):
            found.add(name)
    return found
